### ISSUE TITLE
Dynamic Scopes Management Panel

### ISSUE THREAD

**Issue by misha1235000** [meateam/SpikeClient#2]
### Problem:
According to meateam/ospike#63 issue, We need to allow clients to use scopes in different manner.
### Tasks:
* Create management panel for the scopes mentioned in meateam/ospike#63.
* Adding option for setting scopes when client registered.
* Adding option for other client to requests authorization grants for specific scopes of other client.
* Adding tab for requests made by other clients to use scopes (related to above option).

**Comment by shakedmanes** [comment]
Resolved in cb32cb5a7669e9a5d8917c916b417fc63b01ab68.
